"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const tslib_1 = require("tslib");
const jsx_runtime_1 = require("react/jsx-runtime");
const bs_1 = require("react-icons/bs");
const Panel_1 = tslib_1.__importDefault(require("./Panel"));
const DescriptionPanel = () => {
    return ((0, jsx_runtime_1.jsxs)(Panel_1.default, { initiallyDeployed: true, title: (0, jsx_runtime_1.jsxs)(jsx_runtime_1.Fragment, { children: [(0, jsx_runtime_1.jsx)(bs_1.BsInfoCircle, { className: "text-muted" }), " Description"] }), children: [(0, jsx_runtime_1.jsxs)("p", { children: ["This map represents a ", (0, jsx_runtime_1.jsx)("i", { children: "network" }), " of Wikipedia articles around the topic of \"Data visualisation\". Each", " ", (0, jsx_runtime_1.jsx)("i", { children: "node" }), " represents an article, and each edge a", " ", (0, jsx_runtime_1.jsx)("a", { target: "_blank", rel: "noreferrer", href: "https://en.wikipedia.org/wiki/See_also", children: "\"See also\" link" }), "."] }), (0, jsx_runtime_1.jsxs)("p", { children: ["The seed articles were selected by hand by the", " ", (0, jsx_runtime_1.jsx)("a", { target: "_blank", rel: "noreferrer", href: "https://medialab.sciencespo.fr/", children: "Sciences-Po m\u00E9dialab" }), " ", "team, and the network was crawled using", " ", (0, jsx_runtime_1.jsx)("a", { target: "_blank", rel: "noreferrer", href: "https://densitydesign.github.io/strumentalia-seealsology/", children: "Seealsology" }), ", and then cleaned and enriched manually. This makes the dataset creditable to both the m\u00E9dialab team and", " ", (0, jsx_runtime_1.jsx)("a", { target: "_blank", rel: "noreferrer", href: "https://en.wikipedia.org/wiki/Wikipedia:Wikipedians", children: "Wikipedia editors" }), "."] }), (0, jsx_runtime_1.jsxs)("p", { children: ["This web application has been developed by", " ", (0, jsx_runtime_1.jsx)("a", { target: "_blank", rel: "noreferrer", href: "https://www.ouestware.com/en/", children: "OuestWare" }), ", using", " ", (0, jsx_runtime_1.jsx)("a", { target: "_blank", rel: "noreferrer", href: "https://reactjs.org/", children: "react" }), " ", "and", " ", (0, jsx_runtime_1.jsx)("a", { target: "_blank", rel: "noreferrer", href: "https://www.sigmajs.org", children: "sigma.js" }), ". You can read the source code", " ", (0, jsx_runtime_1.jsx)("a", { target: "_blank", rel: "noreferrer", href: "https://github.com/jacomyal/sigma.js/tree/main/packages/demo", children: "on GitHub" }), "."] }), (0, jsx_runtime_1.jsxs)("p", { children: ["Nodes sizes are related to their", " ", (0, jsx_runtime_1.jsx)("a", { target: "_blank", rel: "noreferrer", href: "https://en.wikipedia.org/wiki/Betweenness_centrality", children: "betweenness centrality" }), ". More central nodes (ie. bigger nodes) are important crossing points in the network. Finally, You can click a node to open the related Wikipedia article."] })] }));
};
exports.default = DescriptionPanel;
//# sourceMappingURL=DescriptionPanel.js.map