/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  sigmaDocSidebar: [
    "index",
    "quickstart",
    "resources",
    {
      type: "category",
      label: "Advanced topics",
      link: {
        type: "generated-index",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "advanced",
        },
      ],
    },
    {
      type: "category",
      label: "Typedoc API",
      link: {
        type: "generated-index",
      },
      items: require("./docs/typedoc/typedoc-sidebar.cjs"),
    },
  ],
};

module.exports = sidebars;
